import sqlite3
import pandas as pd

class DatabaseManager:
    """
    Handles all direct interactions with the SQLite database.
    It executes SQL queries and returns results as Pandas DataFrames.
    """
    
    def __init__(self, db_path: str):
        self.db_path = db_path

    def execute_query(self, sql_query: str) -> dict:
        """
        Executes a SELECT query on the database and returns the results.
        
        Returns:
            dict: Contains 'data' (DataFrame) and 'error' (if any).
        """
        # Safety check: Ensure only SELECT queries are executed
        if not sql_query.upper().strip().startswith("SELECT"):
            return {"error": "Security Alert: Only SELECT statements are allowed."}

        try:
            # Connect to SQLite database
            conn = sqlite3.connect(self.db_path)
            
            # Execute query and load directly into a Pandas DataFrame
            df = pd.read_sql_query(sql_query, conn)
            
            conn.close()
            
            return {
                "data": df,
                "row_count": len(df),
                "error": None
            }
            
        except Exception as e:
            return {"error": f"Database execution failed: {str(e)}"}


# --- Local Testing Block ---
if __name__ == "__main__":
    from config import DB_PATH
    
    print("[INFO] Initializing Database Manager...")
    db_manager = DatabaseManager(db_path=DB_PATH)
    
    # The exact SQL query generated by your Text-to-SQL agent in the previous step
    test_sql = """
    SELECT subject_id, gender, anchor_age 
    FROM patients 
    WHERE gender = 'M' 
    ORDER BY anchor_age DESC 
    LIMIT 5;
    """
    
    print(f"\n[INFO] Executing Query:\n{test_sql}")
    result = db_manager.execute_query(test_sql)
    
    if result["error"]:
        print(f"\n❌ ERROR: {result['error']}")
    else:
        print(f"\n✅ SUCCESS! Retrieved {result['row_count']} rows.")
        print("\n--- Retrieved Data ---")
        print(result["data"])